// council.js — three-voice king's-council reading.
//
// The single biggest UX bet in WorldTwin. Replaces the single AI paragraph
// in the briefing with THREE simultaneous voices (General / Treasurer /
// Augur) that read the same digest through different lenses and disagree
// visibly. Each voice surfaces what only its lens would surface.
//
// Each citation in a voice is clickable → routes to the Data Inspector
// (data-inspector.js) which shows the cache name, the JSON path, the raw
// value, the source URL, the fetch timestamp. This is the "always be able
// to dive into the data behind it all" promise made tactile.
//
// Reads window._cacheStore.get('gemini_narrative').council. Falls back
// silently to the legacy single-paragraph form if the council field isn't
// populated (older aggregator builds, or council generation failed).
(function(){
  const VOICES = [
    {
      id: 'general',
      name: 'The General',
      sigil: '⚔',
      title: 'Strategic · Military',
      hue: 'general',
    },
    {
      id: 'treasurer',
      name: 'The Treasurer',
      sigil: '⚖',
      title: 'Markets · Capital',
      hue: 'treasurer',
    },
    {
      id: 'augur',
      name: 'The Augur',
      sigil: '☄',
      title: 'Climate · Hazards · Slow Signals',
      hue: 'augur',
    },
  ];

  function getCouncilData() {
    const gem = window._cacheStore?.get('gemini_narrative');
    return gem?.council || null;
  }

  function buildVoice(voice, payload) {
    if (!payload) {
      return `<div class="tw-voice tw-voice-${voice.hue} tw-voice-empty">
        <div class="tw-voice-head">
          <span class="tw-voice-sigil">${voice.sigil}</span>
          <span class="tw-voice-name">${voice.name}</span>
          <span class="tw-voice-title">${voice.title}</span>
        </div>
        <div class="tw-voice-body tw-voice-quiet">— silent —</div>
      </div>`;
    }
    const { reading = '', headline = '', citations = [] } = payload;
    const citesHtml = citations.map((c, i) => `
      <button class="tw-cite" data-voice="${voice.id}" data-cite-idx="${i}"
              data-label="${escapeAttr(c.label)}"
              data-value="${escapeAttr(c.value)}"
              data-source="${escapeAttr(c.source)}"
              data-path="${escapeAttr(c.digest_path)}"
              data-date="${escapeAttr(c.data_date || '')}"
              title="Inspect: ${escapeAttr(c.label)} (${escapeAttr(c.data_date || 'date unknown')}) — click to drill into the data">
        <span class="tw-cite-lbl">${escapeHtml(c.label)}</span>
        <span class="tw-cite-v">${escapeHtml(c.value)}</span>
        <span class="tw-cite-src">${escapeHtml(c.source)}${c.data_date ? ` · ${escapeHtml(c.data_date)}` : ''}</span>
      </button>`).join('');
    return `<div class="tw-voice tw-voice-${voice.hue}">
      <div class="tw-voice-head">
        <span class="tw-voice-sigil">${voice.sigil}</span>
        <span class="tw-voice-name">${voice.name}</span>
        <span class="tw-voice-title">${voice.title}</span>
      </div>
      ${headline ? `<div class="tw-voice-headline">${escapeHtml(headline)}</div>` : ''}
      <div class="tw-voice-body">${escapeHtml(reading)}</div>
      ${citesHtml ? `<div class="tw-voice-cites">${citesHtml}</div>` : ''}
    </div>`;
  }

  function escapeHtml(s) {
    return String(s ?? '').replace(/[&<>"']/g, c => ({
      '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  }
  function escapeAttr(s) { return escapeHtml(s).replace(/`/g, '&#96;'); }

  // Render the council into the briefing panel's "Today" slot.
  // If a tw-brief-summary section exists, replace its inner with the council.
  // If not, prepend the council into the briefing body.
  function render() {
    const brief = document.getElementById('twBriefing');
    if (!brief) return;
    const body = brief.querySelector('#twBriefBody') || brief;
    const council = getCouncilData();

    let host = brief.querySelector('.tw-council');
    if (!host) {
      host = document.createElement('div');
      host.className = 'tw-council tw-brief-section';
      // Insert AFTER the head, BEFORE the existing summary (replacing it visually)
      const summary = body.querySelector('.tw-brief-summary');
      if (summary) {
        summary.style.display = 'none';   // hide legacy single-paragraph
        body.insertBefore(host, summary);
      } else {
        body.insertBefore(host, body.firstChild);
      }
    }

    if (!council) {
      host.innerHTML = `<div class="tw-brief-grouplabel">Council</div>
        <div class="tw-council-loading">The council is convening — first reading in a few minutes.</div>`;
      return;
    }

    const synthBadge = council._synthesized
      ? '<span class="tw-council-synth" title="LLM unavailable — voices generated deterministically from the digest. Numbers are real; prose is templated.">deterministic</span>'
      : '<span class="tw-council-llm" title="Generated by an LLM reading the digest, citations validated.">LLM</span>';
    host.innerHTML = `
      <div class="tw-brief-grouplabel">The Council · three voices on one digest ${synthBadge}</div>
      <div class="tw-council-grid">
        ${VOICES.map(v => buildVoice(v, council[v.id])).join('')}
      </div>`;

    // Wire each citation to the Data Inspector
    host.querySelectorAll('.tw-cite').forEach(btn => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        const detail = {
          label: btn.dataset.label,
          value: btn.dataset.value,
          source: btn.dataset.source,
          path: btn.dataset.path,
          voice: btn.dataset.voice,
          data_date: btn.dataset.date,
        };
        if (window.DataInspector?.open) {
          window.DataInspector.open(detail);
        } else {
          // Stub fallback so this works even if inspector isn't loaded yet
          console.log('[council] inspector not loaded; cite =', detail);
        }
      });
    });
  }

  function start() {
    render();
    // Re-render whenever the briefing rebuilds (every 30s) — wrap Briefing.build
    if (window.Briefing && window.Briefing.build && !window.Briefing._councilWrapped) {
      const orig = window.Briefing.build;
      window.Briefing.build = function() {
        orig.apply(this, arguments);
        render();
      };
      window.Briefing._councilWrapped = true;
    }
    setInterval(render, 60000);
    // Aggressive early polling — re-render every 4s for the first 60s so the
    // moment the cache populates from the network we surface it. After 60s
    // the standard 60s interval takes over.
    let n = 0;
    const fast = setInterval(() => {
      render();
      if (++n > 15) clearInterval(fast);
    }, 4000);
  }

  function waitAndStart() {
    if (document.getElementById('twBriefing') && window._cacheStore) {
      start();
    } else {
      setTimeout(waitAndStart, 700);
    }
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => setTimeout(waitAndStart, 1800));
  } else {
    setTimeout(waitAndStart, 1800);
  }

  window.Council = { render, getCouncilData, VOICES };
})();
